### PR TITLE
fix line diff as tslint/formatters/checkstyleFormatter

### PR DESCRIPTION
**Pull request by hiradimir**
I fixed the issue of wrong output line / column.

startPosition of tslint information is start from 0.
but file start usually 1.

I fixed like as original [tslint/formatters/checkstyleFormatter](https://github.com/palantir/tslint/blob/eb047b7125d67ddde22c6ecbf103f9299ca9d806/src/formatters/checkstyleFormatter.ts#L58-L59)

### CODE REVIEW

**Comment by nicolas-schmitt** [comment]
Hey, good catch, thanks for the fix 😸 
I'll publish a new version right away

**Comment by hiradimir** [comment]
Thanks for merge as quickly!

**Comment by nicolas-schmitt** [comment]
Here you go :D
There's a 1.1.1 available

**Comment by hiradimir** [comment]
@nicolas-schmitt  Thanks. I use it!!

**Pull request merged**
